-- SCHEMA: rules_242

-- DROP SCHEMA IF EXISTS rules_242 ;

CREATE SCHEMA IF NOT EXISTS rules_242
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA rules_242 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_242
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_242
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_242
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_242
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;


-- SCHEMA: customer_242

-- DROP SCHEMA IF EXISTS customer_242 ;

CREATE SCHEMA IF NOT EXISTS customer_242
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA customer_242 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_242
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_242
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_242
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_242
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;


-- SCHEMA: data_242

-- DROP SCHEMA IF EXISTS data_242 ;

CREATE SCHEMA IF NOT EXISTS data_242
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_242 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_242
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_242
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_242
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_242
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;
