/* Dev Environment */
-- SCHEMA: data_241

-- DROP SCHEMA IF EXISTS data_241 ;

CREATE SCHEMA IF NOT EXISTS data_241
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_241 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: rules_241

-- DROP SCHEMA IF EXISTS rules_241 ;

CREATE SCHEMA IF NOT EXISTS rules_241
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA rules_241 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: customer_241

-- DROP SCHEMA IF EXISTS customer_241 ;

CREATE SCHEMA IF NOT EXISTS customer_241
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA customer_241 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

/* SIT environment */


-- SCHEMA: data_241_sit

-- DROP SCHEMA IF EXISTS data_241_sit ;

CREATE SCHEMA IF NOT EXISTS data_241_sit
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_241_sit TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_sit
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_sit
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_sit
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_sit
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: rules_241_sit

-- DROP SCHEMA IF EXISTS rules_241_sit ;

CREATE SCHEMA IF NOT EXISTS rules_241_sit
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA rules_241_sit TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_sit
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_sit
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_sit
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_sit
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: customer_241_sit

-- DROP SCHEMA IF EXISTS customer_241_sit ;

CREATE SCHEMA IF NOT EXISTS customer_241_sit
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA customer_241_sit TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_sit
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_sit
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_sit
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_sit
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

/* E2E envrionment */
-- SCHEMA: data_241_e2e

-- DROP SCHEMA IF EXISTS data_241_e2e ;

CREATE SCHEMA IF NOT EXISTS data_241_e2e
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_241_e2e TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_e2e
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_e2e
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_e2e
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_e2e
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: rules_241_e2e

-- DROP SCHEMA IF EXISTS rules_241_e2e ;

CREATE SCHEMA IF NOT EXISTS rules_241_e2e
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA rules_241_e2e TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_e2e
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_e2e
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_e2e
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_e2e
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: customer_241_e2e

-- DROP SCHEMA IF EXISTS customer_241_e2e ;

CREATE SCHEMA IF NOT EXISTS customer_241_e2e
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA customer_241_e2e TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_e2e
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_e2e
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_e2e
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_e2e
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

/* Pilot Environment */
-- SCHEMA: data_241_cert

-- DROP SCHEMA IF EXISTS data_241_cert ;

CREATE SCHEMA IF NOT EXISTS data_241_cert
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_241_cert TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_cert
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_cert
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_cert
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_cert
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: rules_241_cert

-- DROP SCHEMA IF EXISTS rules_241_cert ;

CREATE SCHEMA IF NOT EXISTS rules_241_cert
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA rules_241_cert TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_cert
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_cert
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_cert
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_cert
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: customer_241_cert

-- DROP SCHEMA IF EXISTS customer_241_cert ;

CREATE SCHEMA IF NOT EXISTS customer_241_cert
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA customer_241_cert TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_cert
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_cert
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_cert
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_cert
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

/* PROD Environment */
-- SCHEMA: data_241_prod

-- DROP SCHEMA IF EXISTS data_241_prod ;

CREATE SCHEMA IF NOT EXISTS data_241_prod
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_241_prod TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_prod
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_prod
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_prod
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241_prod
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: rules_241_prod

-- DROP SCHEMA IF EXISTS rules_241_prod ;

CREATE SCHEMA IF NOT EXISTS rules_241_prod
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA rules_241_prod TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_prod
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_prod
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_prod
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241_prod
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: customer_241_prod

-- DROP SCHEMA IF EXISTS customer_241_prod ;

CREATE SCHEMA IF NOT EXISTS customer_241_prod
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA customer_241_prod TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_prod
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_prod
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_prod
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241_prod
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;
