
-- SCHEMA: rules_251

-- DROP SCHEMA IF EXISTS rules_251 ;

CREATE SCHEMA IF NOT EXISTS rules_251
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA rules_251 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_251
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_251
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_251
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_251
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;


-- SCHEMA: customer_251

-- DROP SCHEMA IF EXISTS customer_251 ;

CREATE SCHEMA IF NOT EXISTS customer_251
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA customer_251 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_251
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_251
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_251
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_251
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;


-- SCHEMA: data_251

-- DROP SCHEMA IF EXISTS data_251 ;

CREATE SCHEMA IF NOT EXISTS data_251
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_251 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_251
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_251
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_251
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_251
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;
